version: '3.1'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./conf/postgresql.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5433
    networks:
      - network_app_postgresql_extension
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
networks:
  network_app_postgresql_extension:
